# Generated by Django 5.2.9 on 2026-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('cluster', models.IntegerField()),
                ('predicted_category', models.CharField(max_length=50)),
                ('source', models.CharField(default='Sample', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['doc_id'],
            },
        ),
        migrations.CreateModel(
            name='ClusterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('predicted_cluster', models.IntegerField()),
                ('predicted_category', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
